### ISSUE TITLE
el-get recipe?

### ISSUE THREAD

**Issue by yyr** [tkf/ne2wm#1]
I just tried this out of curiosity..

Frankly it took me a while to figure out what this is about. It would be good if you can provide el-get recipe for this. I know there are decencies to make out first. 

I think el-get  recipe would make it more easy for users to adopt this.

Thanks..

PS: I really liked `ne2wm:dp-code+` and `ne2wm:dp-magit+`. My final conclusion after trying is, I should buy a new big monitor soon :P
Thank you very much for your work to the Emacs world sofar

**Comment by tkf** [comment]
This is originally just my personal settings for e2wm and I just organized it in separated files.  All the great works are by @kiwanami and in e2wm.el.

Well, but there can be some people find my ne2wm first and maybe it's better to provide el-get recipe for them.  I will send a PR to el-get later.  Thanks for your suggestion.
